on:
  push:
    branches:
      - master

jobs:
  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Changed Files
        id: changed
        uses: foodee/pr-includes-file-change@1.0.0
        with:
          paths: ^src/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Dependencies
        if: steps.changed.outputs.matched == 'true'
        run: npm i
      - name: Deploy to GitHub Pages
        if: steps.changed.outputs.matched == 'true'
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  publish_to_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check if version bump
        id: check
        uses: EndBug/version-check@v1.1.1

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: echo "No version change"

      - name: Install deps
        if: steps.check.outputs.changed == 'true'
        run: npm install

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Set NPM Token
        if: steps.check.outputs.changed == 'true'
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish new version
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
