name: Deploy storybook

on:
  push:
    branches:
    - master
    paths:
    - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm i
    - name: Deploy to GitHub Pages
      run: npm run deploy-storybook -- --ci
      env:
        GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
