name: Deploy storybook

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm i
    - name: Build Storybook
      run: npm run build-storybook
    - name: Deploy to GitHub Pages
      run: git push --force --quiet https://${{ secrets.GITHUB_TOKEN }}@github.com/Xapphire13/pancake-layout HEAD:gh-pages
